---
- name: Migrate blog posts to markdown
  hosts: localhost
  gather_facts: false
  vars:
    html_directory: html
    markdown_directory: markdown
    blog_url_file: urls.txt

  tasks:
    - name: Create a directory to store HTML files
      ansible.builtin.file:
        path: "{{ html_directory }}"
        state: directory
        mode: "0755"

    - name: Create a directory to store Markdown files
      ansible.builtin.file:
        path: "{{ markdown_directory }}"
        state: directory
        mode: "0755"

    - name: Read blog post URLs from the file
      ansible.builtin.slurp:
        src: "{{ blog_url_file }}"
      register: urls_content

    - name: Convert blog post URLs to string
      ansible.builtin.set_fact:
        urls_list: "{{ (urls_content['content'] | b64decode).split('\n') | select | list }}"

    - name: Download blog posts to HTML files
      ansible.builtin.uri:
        url: "{{ item }}"
        dest: "{{ html_directory }}/{{ item | basename }}.html"
      with_items: "{{ urls_list }}"

    - name: Register HTML files
      ansible.builtin.find:
        paths: html
        recurse: true
        patterns: "*.html"
      register: html_files

    - name: Loop through HTML files and convert to Markdown
      ansible.builtin.shell:
        cmd: "pandoc -s '{{ item.path }}' -o '{{ markdown_directory }}/{{ item.path | basename | regex_replace(\"\\.html$\", '.md') }}'"
      with_items: "{{ html_files.files }}"
      changed_when: false

    - name: Remove HTML files to clean up
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ html_files.files }}"
