name: Build the Ansible community website

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
    contents: write

jobs:
  lint_templates:
    runs-on: ubuntu-latest
    name: 'Build the website'
    steps:

    - name: Check out the website repository
      uses: actions/checkout@v3

    - name: Pip install nox
      run: python -m pip install nox

    - name: Build the site with nox
      run: python -m nox -s build

    - name: Put the generated site on the build branch 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./output/
        branch: build
        clean: true
