name: Community website CI

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  nikola-build:
    uses: ./.github/workflows/reusable-nikola-build.yml
  nox-sessions:
    uses: ./.github/workflows/reusable-nox.yml
