name: Build and publish the container image

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  IMAGE_NAME: ansible-community/ansible-website
  TAGS: latest
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}

jobs:
  build_dockerfile:
    runs-on: ubuntu-20.04
    name: Build and publish the image
    steps:
    - name: Check out the website repository
      uses: actions/checkout@v3
    - name: Buildah build the website image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAGS }}
        containerfiles: |
          ./Dockerfile
    - name: Push the website image to ghcr.io
      id: push_image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
