name: Build and deploy with Nikola
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build and deploy website to gh-pages'
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ./requirements.txt

    - name: Build the site with Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: true

    - name: Deploy to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./output/
        clean-exclude: previews/
