name: Build and deploy with Nikola
on: 
  push:
    branches:
      - main

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build and deploy website to gh-pages'
    steps:
    - name: Install Dart Sass Embedded
      run: sudo snap install dart-sass-embedded
    - name: Check out
      uses: actions/checkout@v3
    - name: Run Nikola action
      uses: getnikola/nikola-action@v8
