name: Check spelling

on:
  workflow_call:

jobs:
  spell_check:
    runs-on: ubuntu-latest
    name: 'Spelling and word check'
    steps:
    - name: Check out the website repository
      uses: actions/checkout@v3
    - name: Pip install nox
      run: python -m pip install nox
    - name: Spell check the website and blog posts
      run: python -m nox -e spelling
