name: Lint templates

on:
  workflow_call:

jobs:
  lint_templates:
    runs-on: ubuntu-latest
    name: 'Check the website templates for issues'
    steps:
    - name: Check out the website repository
      uses: actions/checkout@v3
    - name: Pip install nox
      run: python -m pip install nox
    - name: Lint the website template files
      run: python -m nox -e lint
