---
name: nox

"on":
    workflow_call:

jobs:
    nox:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - session: lint
                python-versions: "3.13"
              - session: format
                python-versions: "3.13"
              - session: spelling
                python-versions: "3.13"
              - session: build
                python-versions: "3.13"
        name: "Run nox ${{ matrix.session }} session"
        steps:
          - name: Check out repo
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              persist-credentials: false
          - name: Setup nox
            uses: wntrblm/nox@a976d7ee04ab7a13634adc1016d4755a1348225f # 2026.08.17
            with:
              python-versions: "${{ matrix.python-versions }}"
          - name: "Run nox -s ${{ matrix.session }}"
            run: |
              nox -s "${{ matrix.session }}"
