name: Format templates

on:
  workflow_call:

jobs:
  lint_templates:
    runs-on: ubuntu-latest
    name: 'Format website templates'
    steps:
    - name: Check out the website repository
      uses: actions/checkout@v3
    - name: Pip install nox
      run: python -m pip install nox
    - name: Format the website template files
      run: python -m nox -s format
